sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t speedforce7/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true speedforce7/react-test npm test -- --coverage

after_success:
  - docker build -t speedforce7/multi-client ./client
  - docker build -t speedforce7/multi-nginx ./nginx
  - docker build -t speedforce7/multi-server ./server
  - docker build -t speedforce7/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push speedforce7/multi-client
  - docker push speedforce7/multi-nginx
  - docker push speedforce7/multi-server
  - docker push speedforce7/multi-worker


deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-306483622823"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
